copyright: Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International
title: My New Hugo Site


theme: github.com/ros4pro/template-hugo

defaultContentLanguage: fr
defaultContentLanguageInSubdir: true
languages:
  fr:
    languageName: Fran√ßais
    weight: 1
  en:
    languageName: English
    weight: 2
